Blog/config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  resources :articles

  root 'articles#index'

end

Blog/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true
	validates :comment, length: {minimum: 5}
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles=Article.all
	end
	def new
		@article=Article.new
	end
	def create
		@article=Article.new(params_article)
		@article.save
		redirect_to @article
	end
	def show
		@article=Article.find(params[:id])
	end
	private
	def params_article
		params.require(:article).permit(:title,:comment)
	end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Blog/app/views/articles/index.html.erb
<h1><center>Welcome to Blog</center></h1><hr>
<center><strong><%=link_to("New Article",controller: "articles", action: "new", id: @article)%></strong></center>
<hr>
<h1>Articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.comment %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

Blog/app/views/articles/new.html.erb
<h1><center>New Article</center></h1>

<p>
	<%=form_for @article do |f|%>
		<%=f.label :title%>
		<%=f.text_field :title%>
		</p>
		<p>
		
		<%= f.label :comment %>

    	<%= f.text_area :comment %>
    	</p>
    	<p>
    	<%=f.submit%>
    	</p>
	<% end %>

Blog/app/views/articles/show.html.erb
<center><h1>Your Article</h1></center>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= @article.comment %>
</p>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>